# Site settings
baseURL = "https://npb.io/"
languageCode = "en-US"
title = "Nicholas Bayle"
theme = "hugo-split-theme"
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]

  # Metadata for search engines and social sharing
  name = "Nicholas Bayle"
  description = "Split is a centrally-divided layout for a professional online presence with a big image or video left with alongside content."
  shareImage = "images/social.jpg"
  #twitterHandle = "onepagelove"

  # Favicon
  favicon = "favicon.ico"

  # Copyright
  copyright = "&copy;2018 Nicholas Bayle"

  # Section - Content
  [params.content]
    name = "Nicholas Bayle"
    tagline = "Dragon. Detailed. Elderly."
    bio = "Donec at libero id lectus porta dapibus eu in nibh. Cras id mauris sapien. Fusce viverra [luctus urna](#) ac rutrum. Duis semper elit eu mi facilisis eleifend."

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/nick.png"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Connect"

      [[params.links.list1.link]]
        text = "Résumé"
        url = "Nicholas Bayle - Resume.pdf"

      [[params.links.list1.link]]
        text = "Email"
        url = "mailto:nicholas@npb.io"

#      [[params.links.list1.link]]
#        text = "Newsletter"
#        url = "#"

  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Social"

      [[params.links.list2.link]]
        text = "GitHub"
        url = "https://github.com/nbayle"

      [[params.links.list2.link]]
        text = "Instagram"
        url = "https://www.instagram.com/nich_oh_las/"

#      [[params.links.list2.link]]
#        text = "Dribbble"
#        url = "#"

  # Links List #3
#  [[params.links]]
#    [params.links.list3]
#      heading = "Network"

#      [[params.links.list3.link]]
#        text = "Link One"
#        url = "#"

#      [[params.links.list3.link]]
#        text = "Link Two"
#        url = "#"

#      [[params.links.list3.link]]
#        text = "Link Three"
#        url = "#"

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split
